export const GET_ALL_CONTACTS = "GET_ALL_CONTACTS";
export const CREATE_NEW_CONTACT = "CREATE_NEW_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const UPDATE = "UPDATE";
